import Account, { verifySignature } from "./index";

describe("Account", () => {
  let account, data, signature;

  beforeEach(() => {
    account = new Account();
    data = { foo: "foo" };
    signature = account.sign(data);
  });

  describe("verifySignature", () => {
    it("Validates a singnature generated by the account", () => {
      expect(
        verifySignature({
          publicKey: account.address,
          data,
          signature,
        })
      ).toBe(true);
    });
    it("invalidates a signature not generated by the account", () => {
      expect(
        verifySignature({
          publicKey: new Account().address,
          data,
          signature,
        })
      ).toBe(false);
    });
  });
});
